{% set version = "1.1" %}

package:
    name: mcmicro-ilastik
    version: {{ version }}
source:
    -   git_url: https://github.com/ohsu-comp-bio/mcmicro-ilastik.git
        git_rev: {{ version }}

build:
    number: '0'
    string: '0'

requirements:

    run:
        - ilastik-meta=1.3.3post2
        - ilastik-launch
        - python >=3.6
        - scikit-image
        - h5py
        - pandas
        - numpy
        - pathlib
        - tifffile
        - scipy

        
about:
    home: https://github.com/ohsu-comp-bio/mcmicro-ilastik
    summary: "mcmicro module for training and processing large images with Ilastik"
